backend:
  name: github
  repo: JokubasTolocka/freelancePortfolio
  branch: master

media_folder: src/content
public_folder: /content

collections:
  - name: work
    label: Work
    folder: work
    create: true
    fields:
      - { name: id, label: ID, widget: uuid, default }
      - { name: title, label: Title, widget: string }
      - { name: order, label: Order, widget: number }
      - { name: isPrimary, label: Is Primary?, widget: checkbox }
      - { name: subtitle, label: Subtitle, widget: string }
      - { name: coverImageSrc, label: Cover Image Source, widget: string }
      - {
          name: images,
          label: Images,
          widget: list,
          field: { name: imageSrc, label: Image Source Url, widget: string },
        }
      - { name: description, label: Description, widget: markdown }
      - {
          name: tags,
          label: Tags,
          widget: list,
          field: { name: tag, label: Tag, widget: string },
        }
